version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: food_postgres
    environment:
      POSTGRES_DB: food_db
      POSTGRES_USER: food_user
      POSTGRES_PASSWORD: food_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: 