#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Executa o ESLint apenas nos arquivos modificados
git diff --cached --name-only | grep -E '\.(js|jsx|ts|tsx)$' | xargs npx eslint --fix
git add .
